export const LOCAL_USER_META_KEY = 'USER_META_DATA';
export const LOCAL_USER_HISTORY = 'LOCAL_USER_HISTORY';
export const LOCAL_USER_FILTER_QUERY = 'LOCAL_USER_FILTER_QUERY';

export const DEFAULT_MAX_DIFFICULTY = 15;
